# Defaults
packages:
  - 'packages/*'

# Allowed dependency scripts
allowBuilds:
  argon2: true
  prisma: true
  esbuild: true
  vue-demi: true
  '@prisma/client': true
  '@prisma/engines': true
  '@parcel/watcher': true

# Pnpm-specific rules
minimumReleaseAge: 10080
